ARG NGINX_IMAGE=1.31-alpine3.24 \
    NODEJS_IMAGE=26-alpine3.24

FROM node:${NODEJS_IMAGE} AS builder

WORKDIR /app

# Install dependencies
COPY --link ui/package.json ui/package-lock.json .

RUN npm ci --legacy-peer-deps

COPY --link ui/. .

RUN npm run build


FROM nginx:${NGINX_IMAGE} AS ui

# Add nginx configuration
COPY --link nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN set -ex \
    && rm -rf ./* \
    && apk add --no-cache tzdata

# Copy static assets from builder stage
COPY --link --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80/tcp

STOPSIGNAL SIGQUIT

CMD ["nginx", "-g", "daemon off;"]
