upstream awg_api {
    server 172.30.0.4:8080;
}

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # React SPA Routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Healthcheck
    location /health {
        access_log off;
        return 200;
    }

    # API Reverse Proxy to Go Backend container
    location /api/ {
        proxy_pass http://awg_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
