import {
  MdAdd,
  MdArrowDownward,
  MdArrowForward,
  MdArrowUpward,
  MdCheck,
  MdCheckCircle,
  MdClose,
  MdContentCopy,
  MdDarkMode,
  MdDelete,
  MdDns,
  MdDownload,
  MdGroups,
  MdHearing,
  MdHub,
  MdInfo,
  MdInsights,
  MdKey,
  MdLan,
  MdLightMode,
  MdLock,
  MdLogout,
  MdMoreHoriz,
  MdNetworkCheck,
  MdNotifications,
  MdPerson,
  MdPublic,
  MdQrCode2,
  MdRouter,
  MdSave,
  MdSecurity,
  MdSettings,
  MdShield,
  MdSignalCellularAlt,
  MdSpaceDashboard,
  MdSpeed,
  MdTune,
  MdUpload,
  MdVpnKey,
  MdVpnLock,
  MdWarning,
  MdWifi,
  MdSearch,
  MdSchedule,
  MdMonitorHeart,
} from 'react-icons/md';
import {
  MdOutlineDarkMode,
  MdOutlineDns,
  MdOutlineGroups,
  MdOutlineInsights,
  MdOutlineLightMode,
  MdOutlineNotifications,
  MdOutlineRouter,
  MdOutlineSearch,
  MdOutlineSettings,
  MdOutlineSpaceDashboard,
  MdOutlineSpeed,
  MdOutlineTune,
  MdOutlineVpnKey,
  MdOutlineWifi,
} from 'react-icons/md';

const defaultSize = 20;

export function Icon({ icon: IconComponent, size = defaultSize, className = '' }) {
  return <IconComponent size={size} className={className} aria-hidden="true" />;
}

export function NavIcon({ active, filled: Filled, outlined: Outlined, className = '', size = 20 }) {
  const Component = active ? Filled : Outlined;
  return <Component size={size} className={className} aria-hidden="true" />;
}

export const AppIcons = {
  add: MdAdd,
  arrowForward: MdArrowForward,
  arrowUp: MdArrowUpward,
  arrowDown: MdArrowDownward,
  check: MdCheck,
  checkCircle: MdCheckCircle,
  close: MdClose,
  copy: MdContentCopy,
  darkMode: MdDarkMode,
  darkModeOutline: MdOutlineDarkMode,
  delete: MdDelete,
  dns: MdDns,
  dnsOutline: MdOutlineDns,
  download: MdDownload,
  groups: MdGroups,
  groupsOutline: MdOutlineGroups,
  // Endpoint / public address
  hub: MdPublic,
  public: MdPublic,
  info: MdInfo,
  insights: MdInsights,
  insightsOutline: MdOutlineInsights,
  key: MdKey,
  lan: MdLan,
  lightMode: MdLightMode,
  lightModeOutline: MdOutlineLightMode,
  lock: MdLock,
  logout: MdLogout,
  // Active tunnels / VPN connections
  monitorHeart: MdVpnKey,
  monitorHeartFilled: MdVpnKey,
  moreHoriz: MdMoreHoriz,
  networkCheck: MdNetworkCheck,
  notifications: MdNotifications,
  notificationsOutline: MdOutlineNotifications,
  person: MdPerson,
  qrCode: MdQrCode2,
  // Interface / router
  router: MdRouter,
  routerOutline: MdOutlineRouter,
  save: MdSave,
  schedule: MdSchedule,
  search: MdSearch,
  searchOutline: MdOutlineSearch,
  security: MdSecurity,
  settings: MdSettings,
  settingsOutline: MdOutlineSettings,
  shield: MdShield,
  signal: MdSignalCellularAlt,
  spaceDashboard: MdSpaceDashboard,
  spaceDashboardOutline: MdOutlineSpaceDashboard,
  speed: MdSpeed,
  speedOutline: MdOutlineSpeed,
  // Listen port
  port: MdHearing,
  tune: MdTune,
  tuneOutline: MdOutlineTune,
  upload: MdUpload,
  vpnKey: MdVpnKey,
  vpnKeyOutline: MdOutlineVpnKey,
  vpnLock: MdVpnLock,
  warning: MdWarning,
  wifi: MdWifi,
  wifiOutline: MdOutlineWifi,
};
