name: AWG Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env: 
  DOCKER_CONTAINER_REGISTRY: ghcr.io
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: actions/checkout@v7

      - name: Uploading release assets
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          files: |
            compose.yaml
            .env.example

  build:
    name: Build ${{ matrix.IMAGE_NAME }}
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - DOCKERFILE: Dockerfile.api
            IMAGE_NAME: api
          - DOCKERFILE: Dockerfile.ui
            IMAGE_NAME: ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.DOCKER_CONTAINER_REGISTRY }}/${{ github.repository }}/${{ matrix.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ needs.release-please.outputs.tag_name }}

      - name: Docker Build and Push
        env: 
          DOCKER_BUILD_SUMMARY: false
        uses: docker/build-push-action@v7
        with:
          file: ${{ matrix.DOCKERFILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
